import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ProblemStore,requiredText } from '../server/focus/store.mjs';
import { ProblemService } from '../server/focus/service.mjs';
import { clientEnvironment,authURL,codexArgs,claudeArgs,CodexClient } from '../server/focus/clients.mjs';
import { parseAnswer,promptFor } from '../server/focus/prompt.mjs';

function fixture(t){const dir=mkdtempSync(join(tmpdir(),'focus-test-'));const store=new ProblemStore(join(dir,'private','memory.sqlite'));t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return {store,dir};}
function result(source){return {reply:'Which constraint is most important?',memories:[{kind:'belief',text:'Mornings may be useful.',source_id:source.id,quote:source.text}],next_question:'Which constraint is most important?',next_step:'Compare the available options.'};}
test('problem and source-linked proposed memory survive reopening',t=>{const {store,dir}=fixture(t);store.create('Make more time for painting');const id=store.add('source','Mornings are quiet.',{title:'Journal'});const src=store.snapshot().entries.find(e=>e.id===id);const p=store.active();store.applyResult(p.id,p.revision,result(src),[src]);assert.equal(store.snapshot().entries.at(-1).status,'proposed');const other=new ProblemStore(join(dir,'private','memory.sqlite'));assert.equal(other.snapshot().entries.at(-1).source_id,id);other.close();assert.equal(statSync(join(dir,'private','memory.sqlite')).mode&0o777,0o600);});
test('rejects a second active problem',t=>{const {store}=fixture(t);store.create('Painting');assert.throws(()=>store.create('Reading'),/Archive/);});
test('restore recovers archived context without allowing two active problems',t=>{const {store}=fixture(t);store.create('Painting');const id=store.active().id;store.archive();store.restore(id);assert.equal(store.active().title,'Painting');assert.throws(()=>store.restore(id),/Archive the current problem/);store.archive();assert.throws(()=>store.restore('missing'),/not found/);});
test('rejects empty and oversized input',()=>{for(const value of [null,undefined,23,'','  ','x'.repeat(16001)])assert.throws(()=>requiredText(value));assert.equal(requiredText(' hi '),'hi');});
test('rejects actions without an active problem',t=>{const {store}=fixture(t);assert.throws(()=>store.add('user','hi'),/Choose/);});
test('rejects invalid brief field types and length without changing data',t=>{const {store}=fixture(t);store.create('Painting');for(const outcome of [42,'x'.repeat(4001)])assert.throws(()=>store.editBrief({outcome}));assert.equal(store.active().brief.outcome,'');});
test('retrieval stays within the active problem and excludes forgotten memory and assistant guesses',t=>{const {store}=fixture(t);store.create('Painting');store.add('source','Secret painting constraint');store.archive();store.create('Reading');store.add('source','Read a short novel',{title:'Library notes'});store.add('assistant','Secret painting constraint');store.add('belief','Secret painting constraint',{status:'forgotten'});assert.deepEqual(store.retrieve('Secret painting constraint'),[]);assert.equal(store.retrieve('novel')[0].title,'Library notes');});
test('rejects unsupported, missing, or fabricated memory citations atomically',t=>{const {store}=fixture(t);store.create('Painting');const src=store.snapshot().entries[0],p=store.active(),before=store.snapshot().entries.length;for(const memory of [{kind:'secret',source_id:src.id,quote:src.text},{kind:'fact',source_id:'missing',quote:src.text},{kind:'fact',source_id:src.id,quote:'fabricated'},{kind:'fact',source_id:src.id,quote:''}]){assert.throws(()=>store.applyResult(p.id,p.revision,{reply:'Reply',memories:[{text:'Claim',...memory}]},[src]));assert.equal(store.snapshot().entries.length,before);}});
test('stale answer cannot overwrite a revised brief or a different problem',t=>{const {store}=fixture(t);store.create('Painting');const p=store.active();store.editBrief({outcome:'Finish a landscape'});assert.throws(()=>store.applyResult(p.id,p.revision,{reply:'Old'},[]),/superseded/);store.archive();store.create('Reading');assert.throws(()=>store.applyResult(p.id,store.active().revision,{reply:'Old'},[]),/superseded/);});
test('memory actions validate kind, action and ownership',t=>{const {store}=fixture(t);store.create('Painting');const src=store.snapshot().entries[0];assert.throws(()=>store.decide(src.id,'confirm'),/not found/);assert.throws(()=>store.decide(src.id,'erase'),/Unknown/);const id=store.add('belief','Morning is useful',{status:'proposed'});store.decide(id,'confirm');assert.equal(store.snapshot().entries.at(-1).status,'confirmed');store.decide(id,'forget');assert.equal(store.snapshot().entries.at(-1).status,'forgotten');const kept=store.add('belief','Synthetic kept claim');store.archive();store.create('Reading');assert.throws(()=>store.decide(kept,'confirm'),/not found/);});
test('model failure saves the user message without fabricating a reply',async t=>{const {store}=fixture(t);store.create('Painting');const service=new ProblemService(store,{chatgpt:{answer:async()=>{throw new Error('offline');}}});await assert.rejects(service.send('Mornings are hard'),/offline/);assert.equal(store.snapshot().entries.at(-1).text,'Mornings are hard');assert.equal(store.snapshot().entries.filter(e=>e.kind==='assistant').length,0);assert.equal(service.job,null);});
test('overlapping sends, provider changes, and logout are blocked while answering',async t=>{const {store}=fixture(t);store.create('Painting');let finish,calls=0;const service=new ProblemService(store,{chatgpt:{answer:()=>++calls===1?new Promise(r=>finish=r):Promise.resolve({reply:'Unexpected second answer',memories:[]})}});const pending=service.send('Help');await assert.rejects(service.send('Another'),/already/);await assert.rejects(service.call('provider',{provider:'claude'}),/Stop/);await assert.rejects(service.call('logout'),/Stop/);finish({reply:'One answer',memories:[]});await pending;assert.equal(store.snapshot().entries.filter(e=>e.kind==='assistant').length,1);});
test('cancelled result is discarded even if provider ignores the abort signal',async t=>{const {store}=fixture(t);store.create('Painting');let finish;const service=new ProblemService(store,{chatgpt:{answer:()=>new Promise(r=>finish=r)}});const pending=service.send('Help');service.stop();finish({reply:'Late answer',memories:[]});await assert.rejects(pending,/superseded/);assert.equal(store.snapshot().entries.filter(e=>e.kind==='assistant').length,0);});
test('unknown provider and action fail without touching accounts',async t=>{const {store}=fixture(t);const service=new ProblemService(store,{});await assert.rejects(service.call('provider',{provider:'unknown'}));await assert.rejects(service.call('buyCredits'));});
test('source retrieval and context expose matched evidence and recent user text',t=>{const {store}=fixture(t);store.create('Painting');store.add('source','Quiet mornings are best',{title:'Past conversation'});store.add('user','Can mornings help?');const context=store.context('mornings');assert.equal(context.evidence.some(e=>e.kind==='source'&&e.matched.includes('mornings')),true);assert.equal(context.recent.at(-1).text,'Can mornings help?');assert.match(promptFor(context),/untrusted evidence/);});
test('login URLs cannot open non-provider sites or credential-bearing addresses',()=>{for(const url of ['http://auth.openai.com','https://auth.openai.com.attacker.invalid','https://evil.invalid','file:///tmp/x','https://user:password@chatgpt.com'])assert.throws(()=>authURL(url));assert.equal(authURL('https://auth.openai.com/authorize'),'https://auth.openai.com/authorize');});
test('official clients receive no ambient provider secrets',()=>{assert.deepEqual(clientEnvironment({HOME:'/tmp/synthetic',PATH:'/bin',OPENAI_API_KEY:'synthetic',CLAUDE_CODE_OAUTH_TOKEN:'synthetic',ANTHROPIC_API_KEY:'synthetic'}),{HOME:'/tmp/synthetic',PATH:'/bin'});});
test('unrequested RPC tools and token requests are rejected',()=>{const c=new CodexClient('/tmp/synthetic',null);let sent;c.write=m=>sent=m;c.receive({id:7,method:'account/chatgptAuthTokens/refresh',params:{}});assert.equal(sent.error.code,-32601);assert.equal(sent.result,undefined);});
test('client launches retain tool restrictions and official auth modes',()=>{const c=codexArgs(),a=claudeArgs();for(const f of ['shell_tool','plugins','hooks','browser_use','multi_agent'])assert.equal(c[c.indexOf(f)-1],'--disable');assert.ok(c.includes('web_search="disabled"'));assert.equal(a[a.indexOf('--tools')+1],'');assert.ok(a.includes('--safe-mode'));assert.ok(a.includes('--no-session-persistence'));assert.ok(!a.includes('--bare'));});
test('malformed provider text never becomes a plausible answer',()=>{assert.throws(()=>parseAnswer('A believable but invalid response'),/unreadable/);assert.deepEqual(parseAnswer('```json\n{"reply":"hello"}\n```'),{reply:'hello'});});
